package model;
// Generated Jan 15, 2016 7:22:11 PM by Hibernate Tools 4.3.1



/**
 * UnitDealer generated by hbm2java
 */
public class UnitDealer  implements java.io.Serializable {


     private UnitDealerId id;
     private Dealers dealers;
     private Units units;
     private double price;

    public UnitDealer() {
    }

    public UnitDealer(UnitDealerId id, Dealers dealers, Units units, double price) {
       this.id = id;
       this.dealers = dealers;
       this.units = units;
       this.price = price;
    }
   
    public UnitDealerId getId() {
        return this.id;
    }
    
    public void setId(UnitDealerId id) {
        this.id = id;
    }
    public Dealers getDealers() {
        return this.dealers;
    }
    
    public void setDealers(Dealers dealers) {
        this.dealers = dealers;
    }
    public Units getUnits() {
        return this.units;
    }
    
    public void setUnits(Units units) {
        this.units = units;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


