package model;
// Generated Jan 15, 2016 7:22:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Units generated by hbm2java
 */
public class Units  implements java.io.Serializable {


     private Integer unitId;
     private Units units;
     private String type;
     private int isPart;
     private Set unitDealers = new HashSet(0);
     private Set unitses = new HashSet(0);

    public Units() {
    }

	
    public Units(String type, int isPart) {
        this.type = type;
        this.isPart = isPart;
    }
    public Units(Units units, String type, int isPart, Set unitDealers, Set unitses) {
       this.units = units;
       this.type = type;
       this.isPart = isPart;
       this.unitDealers = unitDealers;
       this.unitses = unitses;
    }
   
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    public Units getUnits() {
        return this.units;
    }
    
    public void setUnits(Units units) {
        this.units = units;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getIsPart() {
        return this.isPart;
    }
    
    public void setIsPart(int isPart) {
        this.isPart = isPart;
    }
    public Set getUnitDealers() {
        return this.unitDealers;
    }
    
    public void setUnitDealers(Set unitDealers) {
        this.unitDealers = unitDealers;
    }
    public Set getUnitses() {
        return this.unitses;
    }
    
    public void setUnitses(Set unitses) {
        this.unitses = unitses;
    }




}


