package model;
// Generated Jan 16, 2016 4:33:02 PM by Hibernate Tools 4.3.1



/**
 * Inventorys generated by hbm2java
 */
public class Inventorys  implements java.io.Serializable {


     private Integer inventoryId;
     private Dealers dealers;
     private String name;
     private String address;

    public Inventorys() {
    }

    public Inventorys(Dealers dealers, String name, String address) {
       this.dealers = dealers;
       this.name = name;
       this.address = address;
    }
   
    public Integer getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }
    public Dealers getDealers() {
        return this.dealers;
    }
    
    public void setDealers(Dealers dealers) {
        this.dealers = dealers;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


